services:
  deoldify:
    command: python inference_video.py --file_name video.mp4 --model_name default_model
    container_name: deoldify
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    image: deoldify
    restart: 'no'
    stdin_open: true
    tty: true
    volumes:
    - ./video/intermediate_1:/video/source
    - ./video/intermediate_2:/video/result
  esrgan:
    command: python colorize_video.py --file_name video.mp4 --render_factor 30
    container_name: esrgan
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    image: esrgan
    restart: 'no'
    stdin_open: true
    tty: true
    volumes:
    - ./video/intermediate_3:/video/source
    - ./video/result:/video/results
  neural_style:
    command: python inference_realesrgan_video.py -i /video/source/video.mp4 -n RealESRGAN_x4plus
      --outscale 4.0
    container_name: neural_style
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    image: video-style-transfer
    restart: 'no'
    stdin_open: true
    tty: true
    volumes:
    - ./video/intermediate_2:/video/source
    - ./video/intermediate_3:/video/result
  rife_ai:
    command: python inference_video.py --video /video/source/video.mp4 --output /video/result/video.mp4
    container_name: rife_ai
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    image: rife-container
    restart: 'no'
    stdin_open: true
    tty: true
    volumes:
    - ./video/source:/video/source
    - ./video/intermediate_1:/video/result
version: '3.8'
