
version: '3.8'
services:
  rife-ai:
    image: rife-container
    container_name: rife_ai
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RUN_RIFE=true
    volumes:
      - ./video/source:/video/source
      - ./video/intermediate_1:/video/result
      - ./scripts:/scripts
    command: bash /scripts/rife.sh
    tty: true
    stdin_open: true
    restart: no

  deoldify:
    image: deoldify
    container_name: deoldify
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RUN_DEOLDIFY=false
    volumes:
      - ./video/intermediate_1:/video/source
      - ./video/intermediate_2:/video/result
      - ./scripts:/scripts
    command: bash /scripts/deoldify.sh
    tty: true
    stdin_open: true
    restart: no

  neural_style:
    image: video-style-transfer
    container_name: neural_style
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RUN_NEURAL_STYLE=false
    volumes:
      - ./video/intermediate_1:/video/source
      - ./video/intermediate_3:/video/result
      - ./scripts:/scripts
    command: bash /scripts/neural_style.sh
    tty: true
    stdin_open: true
    restart: no

  esrgan:
    image: esrgan
    container_name: esrgan
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RUN_ESRGAN=false
    volumes:
      - ./video/intermediate_1:/video/source
      - ./video/result:/video/results
      - ./scripts:/scripts
    command: bash /scripts/esrgan.sh
    tty: true
    stdin_open: true
    restart: no
